name = "projects"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-05-25"

[vars]
GITHUB_PAT = "ghp_L8MgOVHKvmKcM"
GITHUB_PAT2 = "prutwhjYDtPPUSIXI1iNxxT"