name = "projects"
main = "./index.js"
type = "webpack"

account_id = "f333d0427dfa7055547fcf4c072d9411"
workers_dev = true
route = "projects"
zone_id = ""
compatibility_date = "2022-05-25"

[vars]
GIT_PRIVATE_ACCESS_TOKEN = "null"