name = "clients"
main = "./index.js"
type = "webpack"

account_id = "f333d0427dfa7055547fcf4c072d9411"
workers_dev = true
zone_id = ""
compatibility_date = "2022-06-05"

kv_namespaces = [ 
  { binding = "CLIENTS", id = "f2835a9105e34d9fa4590045cc03670e" }
]