name = "platforms"
main = "./index.js"
type = "webpack"

account_id = "f333d0427dfa7055547fcf4c072d9411"
workers_dev = true
zone_id = ""
compatibility_date = "2022-06-12"
node_compat = true

kv_namespaces = [ 
  { binding = "ISTRAV", id = "be14263f05194916a40d1bcced0587ca" }
]

# r2_buckets = [
#   { binding = 'ISTRAV', bucket_name = 'istrav' }
# ]