name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      # /websites
      - name: Websites Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'websites'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Publish Websites
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'websites'
          preCommands: npm install
          command: publish
      # /reports
      - name: Reports Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'reports'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Publish Reports
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'reports'
          preCommands: npm install
          command: publish
      # /levels
      - name: Levels Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'levels'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Levels Platforms
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'levels'
          preCommands: npm install
          command: publish
      # /platforms
      - name: Platforms Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'platforms'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Publish Platforms
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'platforms'
          preCommands: npm install
          command: publish
      # /access-keys
      - name: Namespaces Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'access-keys'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Publish Namespaces
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'access-keys'
          preCommands: npm install
          command: publish
      # /namespaces
      - name: Namespaces Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'namespaces'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Publish Namespaces
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'namespaces'
          preCommands: npm install
          command: publish
      # /clients
      - name: Clients Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'clients'
          command:  --help | echo "${{ secrets.API_KEYS_SECRET }}" | wrangler secret put API_KEYS_SECRET
      - name: Publish Clients
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'clients'
          preCommands: npm install
          command: publish
      # /global
      - name: Publish Global
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'global'
          command: publish
      # /projects
      - name: Projects Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'projects'
          # we need --help because GHA places "wrangler" infront of each command so it cancels that out
          command:  --help | echo "${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}" | wrangler secret put GH_PRIVATE_ACCESS_TOKEN
      - name: Publish Projects
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'projects'
          command: publish
      # /license-keys
      - name: LicenseKeys Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'license-keys'
          command:  --help | echo "${{ secrets.LICENSE_KEYS_SECRET }}" | wrangler secret put LICENSE_KEYS_SECRET
      - name: LicenseKeys Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'license-keys'
          command:  --help | echo "${{ secrets.LICENSE_KEYS_PASSWORD }}" | wrangler secret put LICENSE_KEYS_PASSWORD
      - name: Publish LicenseKeys
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'license-keys'
          preCommands: npm install
          command: publish