name: Deploy

on:
  workflow_dispatch:
    inputs:
      GH_PRIVATE_ACCESS_TOKEN:
        description: 'Choose an environment to deploy to: <dev|staging|prod>'
        required: true
        default: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Secrets
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'projects'
          command: echo "${{ github.event.inputs.GH_PRIVATE_ACCESS_TOKEN }}" | wrangler secret put GH_PRIVATE_ACCESS_TOKEN
          
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'projects'
          command: wrangler publish